### ISSUE TITLE
how do we use text with this driver

### ISSUE THREAD

**Issue by Ryan-AD** [carlfriess/GC9A01_demo#1]
Got your demo working, do you know of any libraries or anything that can be used to easily make text on this display?

**Comment by carlfriess** [comment]
Thanks for your interest! Unfortunately, text rendering is out of scope for this project. It's just a simple demo for a driver that uses 18-bit colors on the GC9A01. Most other drivers use 16-bit colors.
Feel free to build on this code but I don't plan on implementing text rendering in this project. There are many other libraries that support text rendering. For example, there is a Arduino library by the manufacturer [here](https://www.buydisplay.com/arduino/ER-TFTM1.28-1_Arduino_Tutorial.zip).
I am working on more complex graphics for this display in [this project](https://github.com/carlfriess/phase). However, that's targeting the [nRF52](https://www.nordicsemi.com/Products/Low-power-short-range-wireless/nRF52832) and it's still in very early stages.
Hope this helps a little! Good luck with your project! :)
